add checkbox in enhancer options  to use default or custom parameters
novius/novius_onlinemediafiles pull request #27
Opened 2017-05-30 13:05 UTC by cholletNovius

2017-05-30 13:36 UTC, jguyomard requested changes

2017-05-30 13:36 UTC, jguyomard commented on classes/controller/front.ctrl.php
> +
trailing space :)

2017-05-30 13:36 UTC, jguyomard commented on classes/driver/oembed.php
> +		//dd($params);
Hum

2017-05-30 13:36 UTC, jguyomard commented on lang/fr/common.lang.php
> +
trailing space :)

2017-05-30 13:36 UTC, jguyomard commented on classes/controller/front.ctrl.php
> +        if ($defaultEmbed = \Arr::get($args, 'media_use_default_embed_display')) {
No assignation in a `if` please

2017-05-30 13:41 UTC, Meroje requested changes

2017-05-30 13:41 UTC, Meroje commented on classes/driver/soundcloud.php
> +    /**
this file has mixed indents, would be nice to fix that

2017-05-30 13:41 UTC, Meroje commented on classes/driver/soundcloud.php
> +                'src' => '//w.soundcloud.com/player/?visual=true&url='.$this->url().'&show_artwork=true',
protocol relative URIs are bad, just use https

2017-05-30 15:29 UTC, cholletNovius commented
up

2017-05-31 06:50 UTC, jguyomard approved these changes

2017-05-31 07:15 UTC, cholletNovius commented
Meroje ? please

2017-05-31 07:31 UTC, Meroje approved these changes

2017-05-31 07:39 UTC, merged